---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner
    cisco.ios.ios_banner:
      banner: login
      text: |
        Nicolas Cage is the
        Tiger King
      state: present

  - name: Merge provided configuration with device configuration
    cisco.ios.ios_interfaces:
      config:
        - name: GigabitEthernet2
          description: Configured and Merged by Ansible Network
          enabled: true
