- name: Update APT packages
  hosts: homelab
  become: yes
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        cache_valid_time: 3600  # Opcional: mantiene el cache válido durante 1 hora
